bind = "0.0.0.0:4300"
workers = 5
accesslog = "-"  # STDOUT
access_log_format = '%(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"'
loglevel = "debug"
worker_class = "gevent"
worker_connections = 1000
limit_request_field_size = 0
timeout = 240
